# Generated by Django 3.1.7 on 2021-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artid', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=300)),
                ('iscolor', models.BooleanField()),
                ('artcost', models.FloatField()),
                ('artdate', models.DateField()),
                ('artimg', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
